import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });
const nanumSquare = localFont({
  src: [
    { path: "./fonts/NanumSquareOTF_acL.otf", weight: "300", style: "normal" },
    { path: "./fonts/NanumSquareOTF_acR.otf", weight: "400", style: "normal" },
    { path: "./fonts/NanumSquareOTF_acB.otf", weight: "700", style: "normal" },
    { path: "./fonts/NanumSquareOTF_acEB.otf", weight: "800", style: "normal" },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ppong-v3",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={nanumSquare.className}>{children}</body>
    </html>
  );
}
